### ISSUE TITLE
You wrote OpenAL twice

### ISSUE THREAD

**Issue by adambiyad** [Manily04/Universal-runtime-installer-EN#7]

**Comment by Manily04** [comment]
Please provide more information, like where exactly in the code or in which section of the programm. Screenshots help a lot too.

**Comment by Manily04** [comment]
I found the missspelling (without ur help sadly) 
![image](https://github.com/Manily04/Universal-runtime-installer-EN/assets/77436704/3f5fbc6a-47ce-41f7-be21-be172a5c215e)

Nevertheless, thank you for the reported problem. I hope the tool still helped you.

**Comment by adambiyad** [comment]
sorry i was asleep
